name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org
    
    - name: Install NPM Packages
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Compile
      run: npm run build

    - name: Execute Unit Tests
      run: npm run test

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: build/cobertura-coverage.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: websocketrt-js-${{ github.run_number }}
        path: |
          **
          !**/node_modules/**

    - name: Publish NPM Package
      if: github.ref == 'refs/heads/master'
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
